title: Home
description: Blog
show_downloads: true

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://kevincarroll7737.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Srb_"
twitter:
  username: srb01246810
#  admins:
