# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup7
title:            Srbx7
tagline:          Blog
description:      "My way of learning is to take notes by applying others' notes while breaking (fixing) stuff."
url:              https://kevincarroll7737.github.io
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Srbx7
  url:            https://twitter.com/Srbx7

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/kevincarroll7737/
